import type { Metadata } from "next";

import { Roboto } from "next/font/google";
import "./globals.css";

// Font configuration
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["700", "900"], // Optional: Add specific weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${roboto.variable} `}>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
